exports.QUERIES_SINGLE_CHAR = [
    'w',
    'n',
    'i',
    'm',
    'o',
    'g',
    'n',
    'v',
]

exports.QUERIES_PARTIAL = [
    'woshi',
    'ida',
    'north da',
    'ili',
    'missi',
    'mi',
    'okla',
    'geo',
    'new j',
    'norrth',
    'verm',
]

exports.QUERIES_FULL = [
    'calfornia',
    'north dakota',
    'ilinois',
    'oklaoma',
    'wiscconsin',
    'indana',
    'masachusets',
    'new jersey',
    'west verginia',
]


exports.STATES = [
    {id: 1, text: 'Alaska'},
    {id: 2, text: 'Hawaii'},
    {id: 3, text: 'California'},
    {id: 4, text: 'Nevada'},
    {id: 5, text: 'Oregon'},
    {id: 6, text: 'Washington'},
    {id: 7, text: 'Arizona'},
    {id: 8, text: 'Colorado'},
    {id: 9, text: 'Idaho'},
    {id: 10, text: 'Montana'},
    {id: 11, text: 'Nebraska'},
    {id: 12, text: 'New Mexico'},
    {id: 13, text: 'North Dakota'},
    {id: 14, text: 'Utah'},
    {id: 15, text: 'Wyoming'},
    {id: 16, text: 'Alabama'},
    {id: 17, text: 'Arkansas'},
    {id: 18, text: 'Illinois'},
    {id: 19, text: 'Iowa'},
    {id: 20, text: 'Kansas'},
    {id: 21, text: 'Kentucky'},
    {id: 22, text: 'Louisiana'},
    {id: 23, text: 'Minnesota'},
    {id: 24, text: 'Mississippi'},
    {id: 25, text: 'Missouri'},
    {id: 26, text: 'Oklahoma'},
    {id: 27, text: 'South Dakota'},
    {id: 28, text: 'Texas'},
    {id: 29, text: 'Tennessee'},
    {id: 30, text: 'Wisconsin'},
    {id: 31, text: 'Connecticut'},
    {id: 32, text: 'Delaware'},
    {id: 33, text: 'Florida'},
    {id: 34, text: 'Georgia'},
    {id: 35, text: 'Indiana'},
    {id: 36, text: 'Maine'},
    {id: 37, text: 'Maryland'},
    {id: 38, text: 'Massachusetts'},
    {id: 39, text: 'Michigan'},
    {id: 40, text: 'New Hampshire'},
    {id: 41, text: 'New Jersey'},
    {id: 42, text: 'New York'},
    {id: 43, text: 'North Carolina'},
    {id: 44, text: 'Ohio'},
    {id: 45, text: 'Pennsylvania'},
    {id: 46, text: 'Rhode Island'},
    {id: 47, text: 'South Carolina'},
    {id: 48, text: 'Vermont'},
    {id: 49, text: 'Virginia'},
    {id: 50, text: 'West Virginia'},
]
