exports.QUERIES_SINGLE_CHAR = [
    'w',
    'n',
    'i',
    'm',
    'o',
    'g',
    'n',
    'v',
]

exports.QUERIES_PARTIAL = [
    'woshi',
    'ida',
    'north da',
    'ili',
    'missi',
    'mi',
    'okla',
    'geo',
    'new j',
    'norrth',
    'verm',
]

exports.QUERIES_FULL = [
    'calfornia',
    'north dakota',
    'ilinois',
    'oklaoma',
    'wiscconsin',
    'indana',
    'masachusets',
    'new jersey',
    'west verginia',
]


exports.STATES = [
    {id: 1, title: 'Alaska'},
    {id: 2, title: 'Hawaii'},
    {id: 3, title: 'California'},
    {id: 4, title: 'Nevada'},
    {id: 5, title: 'Oregon'},
    {id: 6, title: 'Washington'},
    {id: 7, title: 'Arizona'},
    {id: 8, title: 'Colorado'},
    {id: 9, title: 'Idaho'},
    {id: 10, title: 'Montana'},
    {id: 11, title: 'Nebraska'},
    {id: 12, title: 'New Mexico'},
    {id: 13, title: 'North Dakota'},
    {id: 14, title: 'Utah'},
    {id: 15, title: 'Wyoming'},
    {id: 16, title: 'Alabama'},
    {id: 17, title: 'Arkansas'},
    {id: 18, title: 'Illinois'},
    {id: 19, title: 'Iowa'},
    {id: 20, title: 'Kansas'},
    {id: 21, title: 'Kentucky'},
    {id: 22, title: 'Louisiana'},
    {id: 23, title: 'Minnesota'},
    {id: 24, title: 'Mississippi'},
    {id: 25, title: 'Missouri'},
    {id: 26, title: 'Oklahoma'},
    {id: 27, title: 'South Dakota'},
    {id: 28, title: 'Texas'},
    {id: 29, title: 'Tennessee'},
    {id: 30, title: 'Wisconsin'},
    {id: 31, title: 'Connecticut'},
    {id: 32, title: 'Delaware'},
    {id: 33, title: 'Florida'},
    {id: 34, title: 'Georgia'},
    {id: 35, title: 'Indiana'},
    {id: 36, title: 'Maine'},
    {id: 37, title: 'Maryland'},
    {id: 38, title: 'Massachusetts'},
    {id: 39, title: 'Michigan'},
    {id: 40, title: 'New Hampshire'},
    {id: 41, title: 'New Jersey'},
    {id: 42, title: 'New York'},
    {id: 43, title: 'North Carolina'},
    {id: 44, title: 'Ohio'},
    {id: 45, title: 'Pennsylvania'},
    {id: 46, title: 'Rhode Island'},
    {id: 47, title: 'South Carolina'},
    {id: 48, title: 'Vermont'},
    {id: 49, title: 'Virginia'},
    {id: 50, title: 'West Virginia'},
]
